# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: backend

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true

# ===================================================================
# Common properties
# ===================================================================
common:
  cors:
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
    allowed-origin-patterns: "*"
    exposed-headers: "Link, X-Total-Count"
    max-age: 1800

  swagger:
    contactEmail: ~
    contactName: ~
    contactUrl: ~
    description: "Backend API documentation"
    license: ~
    licenseUrl: ~
    termsOfServiceUrl: ~
    title: "Backend API"
    version: #project.version#
