# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: backend

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true

  mail:
    host: ${SMTP_HOST:smtp.resend.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:resend}
    password: ${RESEND_API_KEY}
    from: ${MAIL_FROM_ADDRESS:noreply@yourdomain.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  #i18n
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 3600
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
# ===================================================================
# Common properties
# ===================================================================
common:
  cors:
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
    allowed-origin-patterns: "*"
    exposed-headers: "Link, X-Total-Count"
    max-age: 1800

  swagger:
    contactEmail: ~
    contactName: ~
    contactUrl: ~
    description: "Backend API documentation"
    license: ~
    licenseUrl: ~
    termsOfServiceUrl: ~
    title: "Backend API"
    version: #project.version#

app:
  auth:
    # tokens configuration
    access-token-expiration: 3600      # 1 hour
    refresh-token-expiration: 2592000  # 30 days
    remember-me-expiration: 7776000    # 90 days
    email-verification-expiration: 86400 # 24 hours
    password-reset-expiration: 3600    # 1 hour
    jwt-secret: ${JWT_SECRET:JmYR7kP5x4pdPc83IYz4rFjIl3YZ364n}
  
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  logo:
    url: ${APP_LOGO_URL:http://localhost:8080/assets/logo.png}
